apiVersion: apps/v1
kind: Deployment
metadata:
  name: microblog-frontend
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: microblog-frontend
  template:
    metadata:
      labels:
        app: microblog-frontend
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          imagePullPolicy: {{ .Values.frontend.imagePullPolicy }}
          ports:
            - containerPort: 80
