apiVersion: v1
kind: Service
metadata:
  name: microblog-frontend
spec:
  type: LoadBalancer
  selector:
    app: microblog-frontend
  ports:
    - protocol: TCP
      port: {{ .Values.frontend.service.port }}
      targetPort: 80
